IncreationsPMSWeb/Controllers/BOQController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using IncreationsPMSDAL;
using IncreationsPMSDomain;


namespace IncreationsPMSWeb.Controllers
{
    public class BOQController : BaseController
    {
        // GET: BOQ
        public ActionResult Index()
        {
            return View(); 
        }
        public ActionResult BOQPreparing(int Id)
        {
            SubContractorDropDown();
            BOQPreparing objBOQPreparing = new BOQPreparingRepository().GetNewBOQPreparing(Id);
            //objBOQPreparing.projectWorkRefNo = new BOQPreparingRepository().GetRefNo(objBOQPreparing);
            var internalid = BOQPreparingRepository.GetNextRefNo();
            objBOQPreparing.projectWorkRefNo = internalid;

            objBOQPreparing.projectWorkDate = DateTime.Now;
            objBOQPreparing.BOQPreparingItem = new BOQPreparingRepository().GetTaskDetails(Id);
            foreach (var item in objBOQPreparing.BOQPreparingItem)
            {
                item.BOQPreparingItemWork = new List<BOQPreparingItemWork>();
                item.BOQPreparingItemWork.Add(new BOQPreparingItemWork());
                item.BOQPreparingItemWork[0].PlanedStartDate = DateTime.Now;
                item.BOQPreparingItemWork[0].PlanedEndDate = DateTime.Now;
            }


            return View("BOQPreparing", objBOQPreparing);
        }
        [HttpPost]
        public ActionResult BOQPreparing(BOQPreparing model)
        {

            model.CreatedBy = UserID.ToString();
            model.CreatedDate = System.DateTime.Now;
          
            if (!ModelState.IsValid)
            {
                var allErrors = ModelState.Values.SelectMany(v => v.Errors);
                return View(model);
            }
            Result res = new BOQPreparingRepository().Insert(model);
            if (res.Value)
            {
                TempData["Success"] = "Saved Successfully!";
            }
            else
            {

            }
            return RedirectToAction("Index");

        }
        public void SubContractorDropDown()
        {
            ViewBag.SubContractorList = new SelectList(new DropdownRepository().FillSubContractor(), "Id", "Name");
        }
        public ActionResult PendingBOQPreparing(string TaskName = "")
        {

            return PartialView("_PendingBOQPreparing", new BOQPreparingRepository().GetNewBOQPreparing(TaskName));
        }
        public ActionResult ListIndex()
        {
            return View();
        }
        public ActionResult BOQPrepareList()
        {
            List<BOQPreparing> obj = new List<BOQPreparing>();
            obj = new BOQPreparingRepository().GetBOQPreparingList();

            return PartialView("_BOQListGrid", obj);
        }
        public ActionResult ShowDetails(int id)
        {
            if (id == 0)
            {
                TempData["error"] = "That was an invalid/unknown request.";
                return RedirectToAction("Index", "Home");
            }
            BOQPreparingRepository repo = new BOQPreparingRepository();
            SubContractorDropDown();
            BOQPreparing model = repo.GetBOQPreparingView(id);
            return View("BOQPreparing", model);
        }
        [HttpPost]
        public ActionResult ShowDetails(BOQPreparing model)
        {
            //ViewBag.Title = "Edit";
            model.CreatedBy = UserID.ToString();
            model.CreatedDate = System.DateTime.Now;

            var repo = new BOQPreparingRepository();

            //var result1 = new BOQPreparingRepository().CHECK(model.QuerySheetId);
            //if (result1 > 0)
            //{
            //    TempData["error"] = "Sorry! Already Used!";
            //    TempData["QuerySheetRefNo"] = null;
            //    return View("Edit", model);
            //}

            //else
            //{
                try
                {

                    int row = new BOQPreparingRepository().UpdateBOQPreparing(model);

                    TempData["success"] = "Updated successfully" ;
                    TempData["error"] = "";
                    return RedirectToAction("Index");
                }
                //catch (SqlException)
                //{
                //    TempData["error"] = "Some error occured while connecting to database. Please check your network connection and try again.";
                //}
                catch (NullReferenceException)
                {
                    TempData["error"] = "Some required data was missing. Please try again.";
                }
                catch (Exception)
                {
                    TempData["error"] = "Some error occured. Please try again.";
                }
                return RedirectToAction("Index");
            //}

        }
        public ActionResult Delete(int Id)
        {
            ViewBag.Title = "Delete";

            {

                try
                {
                    var ref_no = new BOQPreparingRepository().DeleteBOQPreparing(Id);
                    TempData["success"] = "Deleted Successfully";
                    return RedirectToAction("Index");
                }
                catch (Exception)
                {
                    TempData["error"] = "Oops! Something went wrong!";
                    //TempData["SubRefNo"] = null;
                    return RedirectToAction("ShowDetails", new { id = Id });
                }
            }
        }

        public ActionResult WorkStatus()
        {
            return View();
        }
        public ActionResult PendingWorkStatus(string ProjectEnquiry = "",string TaskName = "", string ClientName="")
        {

            return PartialView("_PendingWorkStatus", new BOQPreparingRepository().GetWorkStatus(ProjectEnquiry,TaskName, ClientName));
        }

        public ActionResult WorkStatusCreate(int Id)
        {
            WorkStatus objWorkStatus = new BOQPreparingRepository().GetWorkStatusCreate(Id);
           objWorkStatus.WorkStatusItem = new BOQPreparingRepository().GetWorkStatusItem(Id);
           return View("WorkStatusCreate", objWorkStatus);
        }
        [HttpPost]
        public ActionResult WorkStatusCreate(WorkStatus model)
        {
            //model.TranDate = System.DateTime.Now;
            //model.CreatedDate = System.DateTime.Now;
            //model.CreatedBy = UserID;
            if (!ModelState.IsValid)
            {
                var allErrors = ModelState.Values.SelectMany(v => v.Errors);
                return View(model);
            }
            Result res = new BOQPreparingRepository().UpdateWorkStatus(model);
            if (res.Value)
            {
                TempData["Success"] = "Saved Successfully!";
            }
            else
            {

            }
            return RedirectToAction("WorkStatus");

        }
    }
}

IncreationsPMSWeb/Views/BOQ/BOQPreparing.cshtml
@model IncreationsPMSDomain.BOQPreparing
@{string actionName = HttpContext.Current.Request.RequestContext.RouteData.Values["action"].ToString(); }

@{
    ViewBag.Title = "BOQPreparing";
}
<script>
    function Exit() {
        var url = '@Url.Action("index", "home")'
        window.location = url;
    }
    function Delete(id) {
        var url = '@Url.Action("Delete")';
        url += "/" + id
        window.location = url;
    }
    function WorkDetails(index) {
        $('div[id$="_WorkDetails_popup"]').addClass('hide');

        $('#work_' + index + '_WorkDetails_popup').removeClass('hide');

    }
    function AddWork(Workindex) {

        var i = 0;
        var no = 1;
        $('#tab_logic_work' + Workindex + ' input[id^="RowWork_"]').each(function () {
            var id = this.id;
            no++;
            var row = Number(id.replace("RowWork_", ""));
            if (row > i) {
                i = row;
            }
        });
        i++;

        var index = (new Date()).getTime(); // unique indexer
        var clone = $('#tab_logic_work' + Workindex + ' #0').clone(); // clone the BatchProducts item

        clone.html($(clone).html().replace(new RegExp("BOQPreparingItem_" + Workindex + "__BOQPreparingItemWork_0__", "g"), 'BOQPreparingItem_' + Workindex + '__BOQPreparingItemWork_' + i + '__'));
        clone.html($(clone).html().replace(new RegExp(".BOQPreparingItemWork\\[0].", "g"), ".BOQPreparingItemWork[" + i + "]."));
        clone.html($(clone).html().replace(/RowWork_0/, 'RowWork_' + i));
        clone.html($(clone).html().replace(new RegExp("DeleteWork\\(0", "g"), "DeleteWork(" + i));
        clone.html($(clone).html().replace(new RegExp("TextChanged\\(" + Workindex + ",0", "g"), "TextChanged(" + Workindex + "," + i));
        clone.html($(clone).html().replace(/sno1/, 'sno' + (i + 1) + ''));
        clone.html($(clone).html().replace(/this,0/, 'this,' + i + ''));
        $("#tab_logic_work" + Workindex).append('<tr id="' + i + '">' + clone.html() + '  </tr>');
        $("#tab_logic_work" + Workindex + " #sno" + (i + 1)).html((i + 1));
        //Append_Date();
        resetValues(Workindex, i);
      
    }
    function resetValues(Workindex,i) {
        $("#BOQPreparingItem_" + Workindex + "__BOQPreparingItemWork_" + i + "__WorkAmount").val(0);
        $("#BOQPreparingItem_" + Workindex + "__BOQPreparingItemWork_" + i + "__SubContractorId").val('');
        $("#BOQPreparingItem_" + Workindex + "__BOQPreparingItemWork_" + i + "__ProjectWorkDescription").val('');
    }
    function Append_Date() {
        $('.form_date').datetimepicker({
            language: 'fr',
            weekStart: 1,
            todayBtn: 1,
            autoclose: 1,
            todayHighlight: 1,
            startView: 2,
            minView: 2,
            forceParse: 0,
            format: 'dd-M-yyyy',
        });
    }
    function DeleteWork(index, Workindex) {

        var i = 0;
        var no = 1;
        $('#tab_logic_work' + Workindex + ' input[id^="RowWork_"]').each(function () {
            var id = this.id;
            no++;
            var row = Number(id.replace("RowWork_", ""));
            if (row > i) {
                i = row;
            }
        });
        i++;

        if (i > 1) {
            $("#tab_logic_work" + Workindex + " #" + index).remove();
            for (var j = index + 1; j < i; j++) {
                var clone = $("#tab_logic_work" + roomindex + "#" + j).clone(true, true);
                clone.html($(clone).html().replace(new RegExp("BOQPreparingItem_" + Workindex + "__BOQPreparingItemWork_" + j + "__", "g"), 'BOQPreparingItem_' + roomindex + '__BOQPreparingItemWork_' + j - 1 + '__'));
                clone.html($(clone).html().replace(new RegExp(".BOQPreparingItemWork\\[" + j + "].", "g"), ".BOQPreparingItemWork[" + j - 1 + "]."));
                clone.html($(clone).html().replace(new RegExp('sno' + (j + 1) + '">' + (j + 1), "g"), 'sno' + (j) + '">' + (j)));
                clone.html($(clone).html().replace("Delete(" + j, "Delete(" + (j - 1)));
                clone.html($(clone).html().replace("RowWork_" + j, "RowWork_" + (j - 1)));
                clone.html($(clone).html().replace("this," + j, "this," + (j - 1)));
                $("#tab_logic_work" + Workindex + " #" + j).html(clone.html());
                $("#BOQPreparingItemWork_" + (j - 1) + "__SlNo").val(j);
                $("#tab_logic_work" + Workindex + " #" + (j)).attr('id', (j - 1));
            }
        }
    }
</script>

<div class="container in content-in">
    <div class="row">
        <h1>BOQ Preparing</h1>
    </div>

    @using (Html.BeginForm(null, null, FormMethod.Post, new { @class = "createFrom", @id = "BOQPreparing" }))


        {
        <div class="row">
            <div class="col-md-12">
                <div class="row">

                    <div class="col-md-1">
                        <label>Ref No</label>
                        @Html.HiddenFor(m => m.ProjectWorkId)
                        @Html.TextBoxFor(m => m.projectWorkRefNo, new { @class = "form_input" })
                    </div>

                    <div class="col-md-2">
                        <label>Date</label>
                        <div class="input-group date form_date" data-date="" data-date-format="dd MM yyyy" data-link-field="dtp_input2" data-link-format="yyyy-mm-dd">
                            @Html.TextBoxFor(m => m.projectWorkDate, new { @class = "form_input", @Value = Model.projectWorkDate.ToString("dd-MMM-yyyy") })
                            <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>
                        </div>
                    </div>

                    <div class="col-md-3">
                        <label>Project</label>
                        @Html.HiddenFor(m => m.ProjectId)
                        @Html.TextBoxFor(m => m.ProjectEnquiry, new { @class = "form_input" })
                    </div>
                    <div class="col-md-3">
                        <label>Client</label>
                        @Html.HiddenFor(m => m.ClientId)
                        @Html.TextBoxFor(m => m.ClientName, new { @class = "form_input" })
                    </div>

                    <div class="col-md-3">
                        <label>Prefered by</label>
                        @Html.TextBoxFor(m => m.PreparedBy, new { @class = "form_input" })
                    </div>

                </div>
            </div>




        </div>


        <hr />



        <div class="table-responsive scroll3">
            @*<span class="filter"><img src="~/Content/images/icon/filter.png" /></span>*@
            <table class="table table-bordered" id="tab_logic">
                <thead>
                    <tr class="grid_heading">
                        <th width="5%">Project No</th>
                        <th width="10%">Date</th>
                        <th width="18%">Milestone</th>
                        <th width="25%">Task</th>
                        <th width="30%">Work Detail</th>
                        <th width="7%" class="text-right">Total Amount</th>


                    </tr>
                </thead>
                <tbody>

                    @for (int i = 0; i < Model.BOQPreparingItem.Count; i++)
                {
                        @*<tr id="Row_ProjectTask_Id_@i">*@
                        <tr>
                            <td>
                                @Html.HiddenFor(m => @Model.BOQPreparingItem[i].ProjectId, new { @class = "form_input", @style = "text-align:left" })
                                @Html.TextBoxFor(m => @Model.BOQPreparingItem[i].ProjectRefNo, new { @class = "form_input", @style = "text-align:center" })
                            </td>
                            <td>
                                <div class="input-group date form_date" data-date="" data-date-format="dd MM yyyy" data-link-field="dtp_input2" data-link-format="yyyy-mm-dd">
                                    @Html.TextBoxFor(model => Model.BOQPreparingItem[i].ProjectDate, new { @class = "form_input", @Value = Model.BOQPreparingItem[i].ProjectDate.ToString("dd-MMM-yyyy") })
                                    <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>
                                </div>
                            </td>

                            <td>
                                @Html.TextBoxFor(m => @Model.BOQPreparingItem[i].MileStoneName, new { @class = "form_input", @style = "text-align:left" })
                            </td>
                            <td>
                                @Html.HiddenFor(m => @Model.BOQPreparingItem[i].ProjectTaskId, new { @class = "form_input", @style = "text-align:left" })
                                @Html.TextBoxFor(m => @Model.BOQPreparingItem[i].TaskName, new { @class = "form_input", @style = "text-align:left" })
                            </td>
                            <td onclick="WorkDetails(@i)" class="grid-cell" value="Work Details" data-toggle="modal" data-target="#WorkDetailspopup"><a href="#" class="WorkDetails">Select Work Details</a></td>

                            <td>
                                @Html.TextBoxFor(m => @Model.BOQPreparingItem[i].TotalAmount, new { @class = "form_input", @readonly = "true", @style = "text-align:right" })
                                @*<input  class="form_input text-right" readonly />*@
                            </td>


                        </tr>
                    }

                    <tr class="grid_heading">
                        <th width="93%" class="text-right" colspan="5">
                            Total
                        </th>
                        <th width="7%" class="text-right">
                            <span id="baseTotal"></span>
                        </th>
                    </tr>
            </table>

        </div>

        <table class="table table-bordered" id="tab_logic">
            <thead>

            </thead>
        </table>


    <!-- Work Details Column Click PopUp -->
        <div id="WorkDetailspopup" class="modal fade" role="dialog">
            <div class="modal-dialog modal-lg" style="width:800px">
                <!-- Modal content-->
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                        <h4 class="modal-title">Work Details</h4>
                    </div>
                    <div class="modal-body">
                        <div id="WorkDetails">
                            @if (Model.BOQPreparingItem != null && Model.BOQPreparingItem.Count > 0)
                            {
                                for (int i = 0; i < Model.BOQPreparingItem.Count; i++)
                                {
                                    ViewBag.currentIndex = i;
                                    <div id="work_@(i)_WorkDetails_popup" class="hide">
                                        @Html.Partial("_WorkDetails", Model)
                                    </div>
                                }
                            }
                        </div>
                    </div>

                </div>
            </div>
        </div>



        <div class="row">
            <hr />
            <div class="col-md-12">
                @if (actionName == "ShowDetails")

                {
                    <button type="button" class="form-button right" onclick="Exit()">Exit</button>
                        <button type="Submit" class="form-button right">Update</button>
                        <button type="button" class="form-button left" onclick="Delete(@Model.ProjectWorkId)">Delete</button>
                }
                else

                {
                    <button type="button" class="form-button right" onclick="Exit()">Exit</button>
                    <button type="submit" class="form-button right">Save</button>
                }
            </div>

        </div>

    }

</div>

IncreationsPMSWeb/Views/BOQ/Index.cshtml
@model List<IncreationsPMSDomain.PendingBOQPreparing>

@{
    ViewBag.Title = "Index";
}

<script>
    function Exit() {
        var url = '@Url.Action("index", "home")'
        window.location = url;
    }
    function Previous()
    {
        var url = '@Url.Action("ListIndex")';
        location.href = url;
    }
    function Select() {
        var url = '@Url.Action("BOQPreparing", "BOQ")'
        window.location = url;
    }
    function Filter() {
         $("#BOQPreparing").addClass("fade");
        var ClientName = $("#ClientName").val().trim();
        var url = '@Url.Action("PendingBOQPreparing")';
        url += "?ClientName=" + encodeURIComponent(ClientName);
        $("#BOQPreparing").load(url, function () {
        $("#BOQPreparing").removeClass("fade");
        });
    }
</script>
<div class="container content-in">
    <div class="row">
        <h1>Pending BOQ Preparing</h1>
    </div>
    <div class="row">
            <div class="col-md-8">
            <div class="row">
                <div class="col-md-3">
                    <label>Client</label>
                    <input id="ClientName" class="form_input" placeholder="Search for Client" onkeyup="Filter()" />
                </div>
                                          
            </div>
        </div>
    </div>
    <br />
    <div id="BOQPreparing">
        @Html.Action("PendingBOQPreparing")
    </div>
    <div class="row">
        <hr />
        @*<div class="col-md-offset-8 col-md-4">*@
            <div class="col-md-12">
                <button type="button" class="form-button right" onclick="Exit()">Exit</button>
                <button type="button" class="form-button" onclick="Previous()">Previous</button>
            </div>
    </div>
</div>

IncreationsPMSWeb/Views/BOQ/ListIndex.cshtml
<script>
    function Exit() {
        var url = '@Url.Action("index", "home")'
        window.location = url;
    }
    function Open(id) {
        var url = '@Url.Action("ShowDetails")';
        url += "?id=" + id;
        //alert(id);
        window.location = url;
    }
</script>
<div class="container content-in">
    <div class="row">
        <h1>BOQ List</h1>
    </div>
    <br />
    <div id="BOQPreparing_list">
        @Html.Action("BOQPrepareList")
    </div>
    <div class="row">
        <hr />
        <div class="col-md-offset-8 col-md-4">
            <button type="button" class="form-button right" onclick="Exit()">Exit</button>
        </div>
    </div>
</div>

IncreationsPMSWeb/Views/BOQ/WorkStatus.cshtml
@model List<IncreationsPMSDomain.WorkStatus>
@{
    ViewBag.Title = "WorkStatus";
}

<script>

    function Exit() {
        var url = '@Url.Action("index", "home")'
        window.location = url;
    }
    function Select() {
        var url = '@Url.Action("WorkStatusCreate", "BOQ")'
        window.location = url;
    }

    function Filter() {
        $("#WorkStatus").addClass("fade");
        var ProjectEnquiry = $("#ProjectEnquiry").val().trim();
        var TaskName = $("#TaskName").val().trim();
        var ClientName = $("#ClientName").val().trim();
        var url = '@Url.Action("PendingWorkStatus")';
        url += "?ProjectEnquiry=" + encodeURIComponent(ProjectEnquiry) + "&TaskName=" + encodeURIComponent(TaskName) + "&ClientName=" + encodeURIComponent(ClientName);
           $("#WorkStatus").load(url, function () {
           $("#WorkStatus").removeClass("fade");
        });
    }
</script>

<div class="container content-in">
    <div class="row">
        <h1>Work Status</h1>
    </div>


    <div class="row">
           <div class="col-md-8">
            <div class="row">

                <div class="col-md-4">
                    <label>Project</label>
                    <input id="ProjectEnquiry" class="form_input" placeholder="Search for Project." onkeyup="Filter()" />
             </div>

                <div class="col-md-4">
                    <label>Task</label>
                    <input id="TaskName" class="form_input" placeholder="Search for TaskName" onkeyup="Filter()" />
                </div>

                <div class="col-md-4">
                    <label>Client</label>
                    <input id="ClientName" class="form_input" placeholder="Search for Client." onkeyup="Filter()" />
                </div>


               </div>
        </div>
      </div>
       <br />
    
        <div id="WorkStatus">
        @Html.Action("PendingWorkStatus")
    </div>





    <div class="row">
        <hr />
        <div class="col-md-offset-8 col-md-4">
        <button type="button" class="form-button right" onclick="Exit()">Exit</button>
        </div>

    </div>




</div>

IncreationsPMSWeb/Views/BOQ/WorkStatusCreate.cshtml
@model IncreationsPMSDomain.WorkStatus
@{string actionName = HttpContext.Current.Request.RequestContext.RouteData.Values["action"].ToString(); }

@{
    ViewBag.Title = "WorkStatusCreate";
}
<script>
    function Exit() {
        var url = '@Url.Action("index", "home")'
        window.location = url;
    }
           
  </script>

<div class="container in content-in">
    <div class="row">
        <h1>Work Status</h1>
    </div>

    @using (Html.BeginForm(null, null, FormMethod.Post, new { @class = "createFrom", @id = "WorkStatus" }))


    {
        <div class="row">
            <div class="col-md-12">
                <div class="row">
                        <div class="col-md-3">
                        <label>Project</label>
                          @Html.TextBoxFor(m => m.ProjectEnquiry, new { @class = "form_input" })
                         </div>
                    <div class="col-md-3">
                        <label>Task</label>
                     @Html.TextBoxFor(m => m.TaskName, new { @class = "form_input" })
                    </div>
                    <div class="col-md-3">
                        <label>Client</label>
                        @Html.TextBoxFor(m => m.ClientName, new { @class = "form_input" })
                    </div>
                </div>
            </div>
            
         </div>

           <hr />



        <div class="table-responsive scroll3">
                <table class="table table-bordered" id="tab_logic">
                <thead>
                    <tr class="grid_heading">
                        <th width="5%">BOQ No</th>
                        <th width="11%">Date</th>
                        <th width="18%">Milestone</th>
                        <th width="20%">Task</th>
                        <th width="25%">Work</th>
                        <th width="18%">Sub Contractor</th>
                        <th width="15%">Amount</th>
                       <th width="15%">% Completion</th>
                        <th width="40%">Remarks</th>
                    </tr>
                </thead>
                <tbody>

                    @for (int i = 0; i < Model.WorkStatusItem.Count; i++)
                   
                        {

                        <tr>
                            <td>
                                @Html.HiddenFor(m => @Model.WorkStatusItem[i].ProjectWorkId, new { @class = "form_input", @style = "text-align:left" })
                                @Html.TextBoxFor(m => @Model.WorkStatusItem[i].projectWorkRefNo, new { @class = "form_input", @style = "text-align:left" })
                            </td>

                            <td>
                                <div class="input-group date form_date" data-date="" data-date-format="dd MM yyyy" data-link-field="dtp_input2" data-link-format="yyyy-mm-dd">
                                    @Html.TextBoxFor(model => Model.WorkStatusItem[i].projectWorkDate, new { @class = "form_input", @Value = Model.WorkStatusItem[i].projectWorkDate.ToString("dd-MMM-yyyy") })
                                    <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>
                                </div>
                            </td>

                            <td>
                                @Html.TextBoxFor(m => @Model.WorkStatusItem[i].MileStoneName, new { @class = "form_input", @style = "text-align:left" })
                            </td>
                            <td>
                               @Html.TextBoxFor(m => @Model.WorkStatusItem[i].TaskName, new { @class = "form_input", @style = "text-align:left" })
                            </td>
                            <td>
                                @Html.HiddenFor(m => @Model.WorkStatusItem[i].ProjectWorkDetailsId, new { @class = "form_input", @style = "text-align:left" })
                                @Html.TextBoxFor(m => @Model.WorkStatusItem[i].ProjectWorkDescription, new { @class = "form_input", @style = "text-align:left" })
                            </td>
                          <td>
                                @Html.TextBoxFor(m => @Model.WorkStatusItem[i].SubName, new { @class = "form_input", @readonly = "true", @style = "text-align:left" })
                           </td>
                            <td>
                                @Html.TextBoxFor(m => @Model.WorkStatusItem[i].WorkAmount, new { @class = "form_input", @readonly = "true", @style = "text-align:right" })
                             </td>
                            <td>
                                @Html.TextBoxFor(m => @Model.WorkStatusItem[i].PercentageComplete, new { @class = "form_input",  @style = "text-align:right" })
                            </td>
                            <td>
                                @Html.TextBoxFor(m => @Model.WorkStatusItem[i].Remarks, new { @class = "form_input",  @style = "text-align:left" })
                            </td>

                        </tr>
                    }

                
            </table>

        </div>
 
        <div class="row">
            <hr />
            <div class="col-md-12">
                <button type="button" class="form-button right" onclick="Exit()">Exit</button>
                <button type="submit" class="form-button right">Save</button>     
                </div>

        </div>

    }

</div>

IncreationsPMSWeb/Views/BOQ/_BOQListGrid.cshtml
@model List<IncreationsPMSDomain.BOQPreparing>

<table class="table table-bordered table-hover">
    <thead>
        <tr class="grid_heading">
            <th width="14%">Ref No.</th>
            <th width="30%">BOQ Date</th>
            <th width="20%">Client</th>
            <th width="30%">Prepared By</th>
            <th width="1%" class="text-center">Select</th>
        </tr>
    </thead>

    <tbody class="grid_row">
        @if (Model.Count > 0)
        {
            foreach (var item in Model)
            {
                <tr>
                    <td>@item.projectWorkRefNo</td>
                    <td>@item.projectWorkDate.ToString("dd-MMM-yyyy")</td>
                    <td>@item.ClientName</td>
                    <td>@item.PreparedBy</td>
                    <td>
                        <center><input type="button" class="form-button5" value="Select" title="Select to view details" onclick="Open(@item.ProjectWorkId)" /></center>
                    </td>
                </tr>
            }
        }
        else
        {
            <tr>
                <td colspan="6">
                    <center><em>No items found!</em></center>
                </td>
            </tr>
        }
    </tbody>
</table>

IncreationsPMSWeb/Views/BOQ/_PendingBOQPreparing.cshtml
@model List<IncreationsPMSDomain.PendingBOQPreparing>
@using GridMvc.Html

<div class="table-responsive scroll3">
    @Html.Grid(Model).Columns(columns =>
{
columns.Add(m => m.ProjectRefNo).Titled("Project No").SetWidth(5);
columns.Add(m => m.ProjectDate).Format("{0:dd/MM/yyyy}").Titled("Date").SetWidth(5);
columns.Add(m => m.ClientName).Titled("Client").SetWidth(20);
columns.Add(m => m.ProjectEnquiry).Titled("Description").SetWidth(15);
columns.Add().Encoded(false).Sanitized(false).SetWidth(5).Css("cent text-center").RenderValueAs(m => @<a href="@Url.Action("BOQPreparing", new { Id = m.ProjectId })">Select</a>);
    }).WithPaging(15)
</div>